### ISSUE TITLE
Request fewer permissions via OAuth

### ISSUE THREAD

**Issue by al-the-x** [airpair/experts.airpair.com#20]
Just tried out the new Expert profiles and started authorizing social networks, but the scope of the permissions requested was a touch too broad. With GitHub, for example, the app was requesting edit permissions on my profile data and write access for every repository. Twitter was requesting similar permissions, including tweeting and modifying profile information. The rest of the social networks were similarly configured.

For security sake, better to request fewer permissions and just read-only whenever possible. I'm not comfortable granting this level of permissions just for profile data.

**Comment by jkresner** [comment]
Thanks, already tracking in this project https://github.com/airpair/airpair-com-v1-issue-tracker/issues/110

**Comment by ZoRDoK** [comment]
No changes

**Comment by jkresner** [comment]
As soon as consult.airpair.com is launched next week there will be no permissions required to create an expert profile.
