### ISSUE TITLE
Current implementation vulnerable to XSS

### ISSUE THREAD

**Issue by stuartpb** [airpair/experts.airpair.com#25]
See https://www.airpair.com/review/552ebbad4a8a7111006200a7 for an example - the submitter included a sample of their HTML, and airpair's review template dutifully *rendered* that HTML. (Then, when I included my reply, the references to `<script>` and `</script` in the inlined JSON completely broke the page.)

**Comment by jkresner** [comment]
Finally got this one patched up thanks!!
